export const names = [
    'methane',
    'ethane',
    'propane',
    'n-butane',
    '2-methylpropane',
    'n-pentane',
    '2-methylbutane',
    '2,2-dimethylpropane',
    'n-hexane',
    '2-methylpentane',
    '3-methylpentane',
    '2,2-dimethylbutane',
    '2,3-dimethylbutane',
    'n-heptane',
    'n-octane',
    'n-nonane',
    'n-decane',
    'ethene',
    'propene',
    '1-butene',
    'cis-2-butene',
    'trans-2-butene',
    '2-methylpropene',
    '1-pentene',
    'propadiene',
    '1,2-butadiene',
    '1,3-butadiene',
    'ethyne',
    'cyclopentane',
    'methylcyclopentane',
    'ethylcyclopentane',
    'cyclohexane',
    'methylcyclohexane',
    'ethylcyclohexane',
    'benzene',
    'toluene',
    'ethylbenzene',
    'o-xylene',
    'methanol',
    'methanethiol',
    'hydrogen',
    'water',
    'hydrogen sulfide',
    'ammonia',
    'hydrogen cyanide',
    'carbon monoxide',
    'carbonyl sulfide',
    'carbon disulfide',
    'helium',
    'neon',
    'argon',
    'nitrogen',
    'oxygen',
    'carbon dioxide',
    'sulfur dioxide',
    'n-undecane',
    'n-dodecane',
    'n-tridecane',
    'n-tetradecane',
    'n-pentadecane'
];